
swagger:
  enabled: true
  docket:
    chat_room_web_server:
      title: 管理服务
      base-package: mao.chat_room_manage



#HTTP格式配置
spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    messages:
      encoding: UTF‐8


#tomcat头信息(用户ip和访问协议)及访问路径配置
server:
  tomcat:
    remote_ip_header: x‐forwarded‐for
    protocol_header: x‐forwarded‐proto
  servlet:
    context‐path: /manage
  use‐forward‐headers: true


#服务监控与管理配置，运维相关
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env